# docker-compose-lgtm.yml for chainvault
services:
  otel-lgtm:
    image: 'grafana/otel-lgtm:latest'
    environment:
      - ENABLE_OBI=true
      - OBI_TARGET=java
    volumes:
      - ./docker-resources/otel-lgtm/prometheus.yaml:/otel-lgtm/prometheus.yaml
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
      - '9090:9090'
  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./logs:/var/log/chainvault:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    environment:
      - ALLOY_OTLP_UPSTREAM=otel-lgtm:4317
    ports:
      - "12345:12345"
      - "4319:4317"
    depends_on:
      otel-lgtm:
        condition: service_healthy