yarnPath: .yarn/releases/yarn-4.13.0.cjs

nodeLinker: node-modules # or pnp (default in Berry)
nmHoistingLimits: workspaces # helps with React/Vite compatibility

# Optional: zero-installs (commit .yarn/cache)
enableGlobalCache: false
